### ISSUE TITLE
Possible to support string interpolation?

### ISSUE THREAD

**Issue by trjate** [ishworkh/docker-image-artifact-upload#2]
Would it require much work to be able to do something like this?
```
      - name: Build final image
        env:
          IMAGE_TAG: ${{ needs.build_image_tag.outputs.image_tag }}
        run: |
          docker build --target final -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .  # --build-arg?
```
....
```
      - name: Upload image to next job
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
```

**Comment by ishworkh** [comment]
Any reason why you are not doing string interpolation in the github action workflow layer ? 
Wouldn't it be possible for you to do like the following in the meantime ? 

```yaml
- name: Build final image
  env:
    IMAGE_TAG: ${{ needs.build_image_tag.outputs.image_tag }}
  run: |
    docker build --target final -t ${{ECR_REGISTRY}}/${{ECR_REPOSITORY}}:${{IMAGE_TAG}} .  # --build-arg?
```
....
```yaml
 - name: Upload image to next job
    uses: ishworkh/docker-image-artifact-upload@v1
    with:
      image: "${{ECR_REGISTRY}}/${{ECR_REPOSITORY}}:${{IMAGE_TAG}}"
```

I suppose you are setting and passing those variables to those steps from somewhere in your workflow.
