### ISSUE TITLE
No support for Build and push action

### ISSUE THREAD

**Issue by rufusnufus** [ishworkh/docker-image-artifact-upload#3]
The following doesn't work:
```yaml
- name: Build and push
   id: docker_build
   uses: docker/build-push-action@v2
   with:
     push: false
     builder: ${{ steps.buildx.outputs.name }}
     tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
     build-args: |
       GIT_HEAD_COMMIT=${{ github.sha }}
       GIT_CURRENT_BRANCH=${{ github.ref }}

- name: Upload image
   uses: ishworkh/docker-image-artifact-upload@v1
   with:
     image: "${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}"
 ```
 
 
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/24591578/132344524-9cb9eb08-656c-4484-86a8-4b5cba9aab3a.png">

**Comment by ishworkh** [comment]
Hi, for the action to be able to package and upload the docker image, it needs to be loaded and made available in local docker images. And because `docker/build-push-action` does not export/load to docker by default, its not found.
To solve this, you will have to configure your `docker/build-push-action` to load exported image to local docker images which can be done like,
```yaml
- name: Build and push
   id: docker_build
   uses: docker/build-push-action@v2
   with:
     push: false
     builder: ${{ steps.buildx.outputs.name }}
     tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
     load: true
     build-args: |
       GIT_HEAD_COMMIT=${{ github.sha }}
       GIT_CURRENT_BRANCH=${{ github.ref }}

- name: Upload image
   uses: ishworkh/docker-image-artifact-upload@v1
   with:
     image: "${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}"
```

_Note_, `load: true` argument

Reference https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#load

Let me know if this helps :)
